# Generated by Django 4.0.4 on 2022-05-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Center',
            field=models.CharField(blank=True, choices=[('OpenLabs Tamale', 'OpenLabs Tamale'), ('OpenLabs Kumasi', 'OpenLabs Kumasi'), ('OpenLabs Accra', 'OpenLabs Accra')], default='None', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_region',
            field=models.CharField(blank=True, choices=[('north', 'Northen Region'), ('ashanti', 'Ashanti Region'), ('accra', 'Greater Accra')], default='None', max_length=250, null=True),
        ),
    ]
