# Generated by Django 4.0.4 on 2022-05-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_center_studentprofile_current_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='Center',
            new_name='center',
        ),
    ]
