# Generated by Django 4.0.4 on 2022-05-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_date_posted_appliedjobs_date_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_link', models.TextField(blank=True, null=True)),
                ('Career_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='center',
            field=models.CharField(choices=[('OpenLabs Tamale', 'OpenLabs Tamale'), ('OpenLabs Kumasi', 'OpenLabs Kumasi'), ('OpenLabs Accra', 'OpenLabs Accra')], default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cv',
            field=models.FileField(default='text.txt', upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
