# Generated by Django 4.0.4 on 2022-05-16 14:10

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='email')),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('usertype', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('GH', 'Ghanaian')], default=None, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='None', max_length=6)),
                ('location', models.CharField(blank=True, choices=[('GH', 'Ghanaian')], default='Ghanaian', max_length=250, null=True)),
                ('profile_image', models.ImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, upload_to=accounts.models.get_profile_image_filepath)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('allowance', models.CharField(blank=True, max_length=200, null=True)),
                ('job_description', models.TextField()),
                ('requirement', models.TextField()),
                ('category', models.CharField(choices=[('Category', 'Category'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intenship', 'Intenship')], max_length=200)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('industry', models.CharField(blank=True, choices=[('IT & Telecoms', 'IT & Telecoms'), ('Automative & Aviation', 'Automative & Aviation'), ('Real Estate', 'Real Estate')], default='Choose', max_length=200, null=True)),
                ('country', models.CharField(blank=True, choices=[('Ghana', 'Ghana')], default='Ghana', max_length=200, null=True)),
                ('region', models.CharField(blank=True, choices=[('Northern Region', 'Northern Region'), ('Greater Accra', 'Greater Accra'), ('Ashanti Region', 'Ashanti Region')], default='Choose', max_length=200, null=True)),
                ('address', models.TextField(blank=True, default='Choose', max_length=300, null=True)),
                ('website', models.CharField(blank=True, max_length=550, null=True)),
                ('profile_image', models.ImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, upload_to=accounts.models.get_profile_image_filepath)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
